name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_URL: "http://localhost:5001/api"

      PORT: 5001
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALLBACK_URL: "http://localhost:5001/api/users/auth/google/callback"

      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

      VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
      VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
      NEXT_PUBLIC_VAPID_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}

      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: "http://localhost:5001"

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: handy-dandy-client
        run: npm install

      - name: Install Playwright Browsers
        working-directory: handy-dandy-client
        run: npx playwright install --with-deps

      - name: Build Next.js app
        working-directory: handy-dandy-client
        run: npm run build

      - name: Start Next.js server
        working-directory: handy-dandy-client
        run: |
          npm start &
          echo "Waiting for Next.js to start..."
          npx wait-on http://localhost:5001

      - name: Run Playwright tests
        working-directory: handy-dandy-client
        run: npx playwright test --reporter=html

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: handy-dandy-client/playwright-report/
          retention-days: 30
